root = "."
tmp_dir = "tmp"

[build]
pre_cmd = ["echo hello air > pre_cmd.txt"]
cmd = "go build -o ./tmp/main.exe ./cmd"
post_cmd = ["echo hello air > post_cmd.txt"]
bin = "tmp\\main.exe"
full_bin = ".\\tmp\\main.exe"
args_bin = ["hello", "world"]
include_ext = ["go", "tpl", "tmpl", "html","json"]
exclude_dir = ["assets", "tmp", "vendor", "frontend/node_modules"]
include_dir = []
include_file = []
exclude_file = []
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
follow_symlink = true
log = "air.log"
poll = false
poll_interval = 500
delay = 0
stop_on_error = true
send_interrupt = false
kill_delay = 500
rerun = false
rerun_delay = 500

[log]
time = true
main_only = false
silent = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true

[proxy]
enabled = true
app_port = 8080
proxy_port = 8090